on:
- push
- pull_request
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - name: +x gradlew
        shell: bash
        run: chmod +x gradlew
      - name: Build and test
        id: build
        shell: bash
        run: ./gradlew :taskshark:build
      - name: Generate documentation
        if: ${{ always() }}
        id: doc
        shell: bash
        run: ./gradlew dokkaGenerate
      - name: Export JARs
        if: ${{ steps.build.outcome == 'success' }}
        uses: actions/upload-artifact@v4
        with:
          path: "taskshark/build/libs/taskshark.jar"
      - name: Export documentation
        if: ${{ steps.doc.outcome == 'success' }}
        uses: actions/upload-artifact@v4
        with:
          path: "taskshark/build/dokka/html/"
