on:
  # Try to run when relevant (releases)
  push:
    tags:
      - v*
  release:
    types: [published, edited]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Always checkout main here regardless of event
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          ref: dev
          # get refs on-demand
          filter: 'tree:0'
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - name: chmod
        shell: bash
        run: |
          chmod +x gradlew publishing/strap.sh publishing/build_all.sh publishing/build_singular.sh
      - name: Build repo
        id: repo
        shell: bash
        run: ./publishing/strap.sh
      - name: Prepare to generate web export
        shell: bash
        id: prepare_export
        run: mkdir -p dist
      - name: Add Dokka to web export
        id: export_dokka
        shell: bash
        if: ${{ steps.repo.outcome == 'success' && steps.prepare_export.outcome == 'success' }}
        run: cp -r build/docs/* dist/
      - name: Add Maven to web export
        id: export_maven
        shell: bash
        if: ${{ steps.repo.outcome == 'success' && steps.prepare_export.outcome == 'success' }}
        run: cp -r build/repo/* dist/
      - name: Set up GitHub Pages
        id: setup_pages
        if: ${{ steps.prepare_export.outcome == 'success' && ( steps.export_dokka.outcome == 'success' || steps.export_maven.outcome == 'success' )}}
        uses: actions/configure-pages@v5
      - name: Upload GitHub Pages artifact
        if: ${{ steps.setup_pages.outcome == 'success' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - name: Publish GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
